name: TAP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - fastapi
  - pandas
  - numpy
  - requests
  - plotly
  - dash
  - dash-bootstrap-components
  - dash-cytoscape
  - networkx
  - python-louvain
  - statsmodels
  - python-multipart
  - jinja2
  - openpyxl
  - xlrd
  - pip:
      - uvicorn[standard]
